MySite/MySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 
    namespace='blog')),
]

MySite/blog/urls.py
from django.urls import path, include
from . import views
app_name = 'blog'

urlpatterns = [
# widoki posta
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('blog/', include('blog.urls', namespace='blog')),

]

MySite/blog/models.py
from django.db import models as m
from django.utils import timezone
from django.conf import settings

class PublishedManager(m.Manager):
    def get_queryset(self):
        return (
            super().get_queryset().filter(status=Post.Status.PUBLISHED)
        )

class Post(m.Model):
    class Status(m.TextChoices):
        DRAFT = 'DF', 'Roboczy'
        PUBLISHED = 'PB', 'Opublikowany'

    title = m.CharField(max_length = 250)
    slug = m.SlugField(max_length = 250)
    author = m.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=m.CASCADE,
        related_name='blog_post'
    )
    body = m.TextField()
    publish = m.DateTimeField(default=timezone.now)
    created = m.DateTimeField(auto_now_add=True)
    updated = m.DateTimeField(auto_now=True)
    status = m.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT
    )    
    objects = m.Manager() # Menedżer domyślny
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            m.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title 

# Coś tu jest solidnie nie tak 

class Product(m.Model):
    class Status(m.TextChoices):
        DRAFT = 'DF', 'Roboczy'
        PUBLISHED = 'PB', 'Opublikowany'

    p_key = m.AutoField(primary_key=True)
    name = m.CharField(max_length = 250)
    price = m.DecimalField(max_digits = 100, decimal_places=2)
    slug = m.SlugField(max_length = 250)

MySite/blog/views.py
from django.shortcuts import render
from django.http import Http404
from .models import Post
from django.shortcuts import get_object_or_404, render
# Create your views here.

def post_list(request):
    posts = Post.published.all()
    return render(
    request,
    'blog/post/list.html',
    {'posts': posts}
    )

def post_detail(request, id):
    try:
        post = Post.published.get(id=id)
        post = get_object_or_404(
            Post,
            id = id,
            status=Post.Status.PUBLISHED
        )
    except Post.DoesNotExist:
        raise Http404("Nie znaleziono posta.")
    return render(
    request,
    'blog/post/detail.html',
    {'post': post}
    )

MySite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div od="sidebar">
        <h2>Mój blog</h2>
        <p>To jest mój blog.</p>
    </div>    
</body>
</html>

MySite/blog/templates/blog/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

MySite/blog/templates/blog/post/list.html
post/list.html: {% extends "blog/base.html" %}
 
{% block title %}Mój blog{% endblock %}

{% block content %}
<h1>Mój blog</h1>

    {% for post in posts %}
<h2>
<a href="{% url 'blog:post_detail' post.id %}">

                {{ post.title }}
</a>
</h2>
<p class="date">

            Opublikowane {{ post.publish }} przez {{ post.author }}
</p>

        {{ post.body|truncatewords:30|linebreaks }}

    {% endfor %}

    {% endblock %}
 